#!/usr/bin/env bash
# configures an Nginx server; /redirect_me redirects to another page.
# redirection is configured as a '301 Moved Permanently'

sudo apt-get update && sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default

touch /var/www/html/index.html
echo 'Hello World!' > /var/www/html/index.html

echo "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;

     location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
