#!/usr/bin/env bash
# Nginx listens to port 80 of all active IPv4 IPs servers
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
