#!/usr/bin/env bash
#FizzBuzz
#FizzBuzz when the number is a multiple of 3 and 5
#Fizz when the number is multiple of 3
#Buzz when the number is a multiple of 5
#Otherwise, displays the number

for ind in {1..100}
do
    if ((ind % 3 == 0 && ind % 5 == 0))
    then
        echo "FizzBuzz"
    elif ((ind % 3 == 0))
    then
        echo "Fizz"
    elif ((ind % 5 == 0))
    then
        echo "Buzz"
    else
        echo "$ind"
    fi
done
